Update master_exploreepicapp.yml

diff --git a/.github/workflows/master_exploreepicapp.yml b/.github/workflows/master_exploreepicapp.yml
--- a/.github/workflows/master_exploreepicapp.yml
+++ b/.github/workflows/master_exploreepicapp.yml
@@ -50,8 +50,14 @@ jobs:
           name: node-app
       - name: List artifact contents
         run: ls -la
+      - name: Check directories before unzipping
+        run: |
+          if [ ! -d "templates" ] || [ ! -d "public" ]; then
+            echo "Missing directories: templates or public"
+            exit 1
+          fi
       - name: Unzip artifact for deployment
-        run: unzip release.zip -d ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
+        run: unzip release.zip -d .
       - name: List unzipped files
         run: ls -la ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
       - name: "Deploy to Azure WebApp"
